### ISSUE TITLE
Question regarding RNaseR corretion

### ISSUE THREAD

**Issue by baylorbiostat** [bioinfo-biols/CIRIquant#16]
Hi Jinyang,

I am trying to use CIRIquant on on our RNaseR samples and I have a couple of questions to seek your advice for.
Looks like after I run RNaseR correction, the corrected counts will be typically much smaller than the original raw counts. Taking your test data as example: in the "case.gtf" file (I assume this is un-corrected RNaseR count), you have circRNA chr1:1192372|1203372 detected and its output is:
circ_id "chr1:1192372|1203372"; circ_type "exon"; bsj 10.0; fsj 47.0; junc_ratio 0.299; gene_id "ENSG00000160087.16"; gene_name "UBE2J2"; gene_type "protein_coding". 
This means chr1:1192372|1203372 has 10 BSJ reads and 47 fsj reads in RNaseR sample, right?

Then, if we got to the "case_corrected.gtf", the output for this circRNA is:
circ_id "chr1:1192372|1203372"; circ_type "exon"; bsj 2.287; fsj 183.000; junc_ratio 0.024; rnaser_bsj 10.000; rnaser_fsj 47.000; gene_id "ENSG00000160087.16"; gene_name "UBE2J2"; gene_type "protein_coding";
From here we can tell this circRNA originally had 10 BSJ and 47 FSJ before correction, and after correction, the BSJ count becomes 2.287 (which is much smaller than the uncorrected BSJ count 10), and FSJ becomes 183.

Finally, if we go to the "CIRI_DE_corrected.csv" file, the stats for this circRNA is:

circRNA_ID | Case_BSJ | Case_FSJ | Case_Ratio | Ctrl_BSJ | Ctrl_FSJ | Ctrl_Ratio | DE_score | DS_score
chr1:1192372|1203372 | 2 | 183 | 0.024 | 1 | 177 | 0.011 | 0 | None
We can see that the DE module rounded the 2.287 corrected BSJ counts to 2.

Above is one example, but in general this is what I observe from ciriquant:
(1) by applying the RNaseR correction, the corrected BSJ counts are no longer integers and they can be much smaller than the initial uncorrected BSJ counts.
(2) To run downstream differential analysis (such like DESeq2 that does not allow non-integer counts), I will need to round them to integers first.
Is my understanding right? Thank you very much for your input in advance.

best,

Jinghua

**Comment by Kevinzjy** [comment]
Hi, Jinghua,

The RNase R correction step in CIRIquant uses a gaussian mixture model to estimate the raw expression values of circRNAs before RNase R treatment, which can reduce the impact of difference in RNase R digestion efficiency between different libraries. Thus, considering that the RNase R treatment can effectively enrich circRNAs, it’s pretty normal that corrected expression values are much smaller than the uncorrected BSJ counts.

If you plan to run differential expression analysis using RNase R treated samples, I would recommend you running CIRI_DE_replicate without RNase R correction. For now, the calculation of DE-score only supports samples without biological replicates.

Best regards,

Jinyang
