### ISSUE TITLE
Can CIRIquant be used with single-end data?

### ISSUE THREAD

**Issue by stiv1n** [bioinfo-biols/CIRIquant#19]
The arguments of the CIRIquant seem to anticipate solely pair-end data.

**Comment by Kevinzjy** [comment]
CIRIquant only supports paired-end RNA-seq data as input.

**Comment by stiv1n** [comment]
Is there an algorithmic reason for that. Like something that CIRI_AS does.

**Comment by Kevinzjy** [comment]
Hi, @stiv1n . We believe that single-end RNA-seq is becoming out-of-date, so no entry for single-end data was implemented in the current version. 

In theory, the CIRIquant strategy can be also applied to single-end data, but still need comprehensive evaluation. Maybe I will add this feature in the future.
