### ISSUE TITLE
Different circRNA prediction tools for differential expression

### ISSUE THREAD

**Issue by prisca399** [bioinfo-biols/CIRIquant#22]
Hi @Kevinzjy ,

In your paper, you report that CIRIquant works excellently for quantification of circRNAs using prediction results from a variety other tools. Do you think you can also comment on the compatibility of CIRIquant's differential expression workflow with different tools? For example, what is the overlap of differentially expressed circRNAs reported using CIRIquant when the prediction results from different tools are used for quantification? This is an analysis I plan to perform on my own dataset, and I would appreciate your insights beforehand!

Prisca

**Comment by Kevinzjy** [comment]
Hi @prisca399 , for DE analysis, CIRIquant uses all gene expression levels to calculate normalization factors, which means we are comparing the circRNA expression levels against all linear mRNAs. 

However, for other tools like circTest, they use a binomial model to compare the BSJ reads of a circRNA against the host genes reads, which can reflect the change of "junction ratio" in CIRIquant output. Thus, results from different DE workflow might reflect expressional changes from different perspectives, so I won't say which one is better and you could choose the tools that fit your needs better.

**Comment by prisca399** [comment]
Thank you, but I think you may have misunderstood my question. By "different tools" for DE analysis I was actually referring to whether you've compared use of the results of different circRNA predictions tools (i.e. CIRI2 vs find_circ vs CE2) upstream of CIRIquant's DE workflow. Certainly let me know if what I am asking is still unclear. Thanks!

**Comment by Kevinzjy** [comment]
I get it. CIRIquant only uses the coordinate information from these prediction tools, so it won't matter a lot which tools you are using. Under most circumstances, we are focusing on the highly expressed circRNAs only, and most tools should work fine on the detection of these transcripts. 

P.S. if you want to get more convincing results, you can use multiple tools for prediction, and use circRNAs that can be detected by more than two tools as input for CIRIquant.

**Comment by prisca399** [comment]
Thanks for the clarification and tip!
