### ISSUE TITLE
Not able to generate the final circ.gtf output

### ISSUE THREAD

**Issue by eltonjrv** [bioinfo-biols/CIRIquant#24]
Dear CIRIquant developers,

After over 1 hour running CIRIquant, I'm getting stuck with following error(s):
#########################################################
[Tue 2021-03-09 03:24:07] [INFO ] Input reads: KH1W_S1318_L004_R1-trimmed_paired.fq.gz,KH1W_S1318_L004_R2-trimmed_paired.fq.gz
[Tue 2021-03-09 03:24:07] [INFO ] Library type: TAKARA SMARTer
[Tue 2021-03-09 03:24:07] [INFO ] Output directory: /nobackup/fbsev/LeedsOmics/Kathy-circRNAs/CIRIquant-run/02-CIRIquant/R_normal_1, Output prefix: R_normal_1
[Tue 2021-03-09 03:24:07] [INFO ] Config: config.yml Loaded
[Tue 2021-03-09 03:24:07] [INFO ] 40 CPU cores availble, using 40
[Tue 2021-03-09 03:24:07] [INFO ] Align RNA-seq reads to reference genome ..
[Tue 2021-03-09 04:02:06] [INFO ] Estimate gene abundance ..
[Tue 2021-03-09 04:08:02] [INFO ] No circRNA information provided, run CIRI2 for junction site prediction ..
[Tue 2021-03-09 04:08:02] [INFO ] Running BWA-mem mapping candidate reads ..
[Tue 2021-03-09 04:16:52] [INFO ] Running CIRI2 for circRNA detection ..
[Tue 2021-03-09 04:30:41] [INFO ] Extract circular sequence
^M[Tue 2021-03-09 04:30:41] [0%   ] [..................................................]Traceback (most recent call last):
  File "/nobackup/fbsev/bioinformatics-tools/CIRIquant/venv/bin/CIRIquant", line 33, in <module>
    sys.exit(load_entry_point('CIRIquant==1.1.1', 'console_scripts', 'CIRIquant')())
  File "/nobackup/fbsev/bioinformatics-tools/CIRIquant/venv/lib/python3.7/site-packages/CIRIquant-1.1.1-py3.7.egg/CIRIquant/main.py", line 183, in main
    out_file = circ.proc(log_file, thread, bed_file, hisat_bam, rnaser_file, reads, outdir, prefix, anchor, lib_type)
  File "/nobackup/fbsev/bioinformatics-tools/CIRIquant/venv/lib/python3.7/site-packages/circ/__init__.py", line 644, in proc
    generate_index(log_file, circ_info, circ_fasta)
  File "/nobackup/fbsev/bioinformatics-tools/CIRIquant/venv/lib/python3.7/site-packages/circ/__init__.py", line 189, in generate_index
    chrom_seq = extract_seq(utils.FASTA, chrom_start, chrom_length)
  File "/nobackup/fbsev/bioinformatics-tools/CIRIquant/venv/lib/python3.7/site-packages/circ/__init__.py", line 141, in extract_seq
    seq = f.read(length)
TypeError: argument should be integer or None, not 'float'
#########################################################

I'm afraid there are uninitialized variables in the code (e.g. length).
Could anyone share a light on how to better solve this?

Thanks very much,
Best,
Elton
PS: I installed the program through your "virtualenv" recommended way (https://ciriquant-cookbook.readthedocs.io/en/latest/installation.html#install-ciriquant-from-source-code). I needed to fix a couple of issues, such as filling up empty __init__.py files from both "CIRIquant/venv/lib/python3.7/site-packages/circ" and "CIRIquant/venv/lib/python3.7/site-packages/pipeline" with the content from circ.py and pipeline.py, respectively (pulled from "CIRIquant/venv/lib/python3.7/site-packages/CIRIquant-1.1.1-py3.7.egg/CIRIquant/" dir). Also, I needed to replace "izip_longest" occurrences to "zip_longest" within circ.py. I'm now a bit concerned on keep handling your code several times which may probably mess everything up in a certain point. Hope you can help. Thanks again!

**Comment by eltonjrv** [comment]
Hi Jyniang,
The program is working smoothly under python 2.7. Thanks again!
I'm just encountering an R error (duplicated rows) in the very final step (CIRI_DE_replicate), which I'll post in a new issue.
Still on this current issue, would you mind if I suggest you to fix the following command from your installation tutorial at https://ciri-cookbook.readthedocs.io/en/latest/CIRIquant_1_installation.html#install-ciriquant-from-source-code
$ virtualenv -p /path/to/your/python2/executable venv
I believe this would prevent others to fall in the same mistake as I did.
Thanks,
Cheers,
Elton

**Comment by Kevinzjy** [comment]
Thanks for the useful advice! I've updated the installation commands accordingly.
