### ISSUE TITLE
Deferentially expressed circRNAs with biological replicate

### ISSUE THREAD

**Issue by ravisaroch** [bioinfo-biols/CIRIquant#45]
Hello, I used CIRIquant to calculate the fold change under a certain situation.

I used the  sample as text files:

**Ciriquant output file:** 
 24_PAU_Case_1 ./AK10_S10.gtf T 1
 24_PAU_Case_2 ./AK11_S11.gtf T 2
 24_PAU_Case_3 ./AK12_S12.gtf T 3
 0_PAU_Control_1 ./AK4_S4.gtf C 1
 0_PAU_Control_2 ./AK5_S5.gtf C 2
 0_PAU_Control_3 ./AK6_S6.gtf C 3

**The below command is use to calculate DE circRNAs**
CIRI_DE_replicate --lib 0_24h_PAU_lib.csv --bsj 0_24h_PAU_circRNA_bsj.csv --gene 0_24_PAU_gene_count_matrix.csv --out 0_24_PAU_DE_Cir.tsv

**It Generate Output file of the DE CircRNA**

Circ_ID	logFC	logCPM	LR	PValue	DE	FDR
4:31022314|31029529	-7.64922634263453	-0.161626549205444	15.0799339995342	0.000103052931416515	0	0.0867705682527054
12:11277575|11320618	6.69328375381015	-1.50848617923073	13.7678102531273	0.000206850296297323	0	0.0870839747411729
12:11262912|11265838	7.65742002735099	-1.98591121764622	12.4043376775065	0.00042833770549839	0	0.120220116009881
3:19812063|19865665	-5.97369371848626	-1.97194836747005	9.66092614644816	0.00188228702661538	0	0.396221419102538
6:3094946|3106151	-6.41385190127333	-3.14131472782527	9.1566548978384	0.00247815160571721	0	0.417320730402778
10:18675348|18689873	7.72459306313907	-1.49011568946911	8.45368794039285	0.00364303965091808	0	0.42321854074561
5:7746966|7747829	5.77609936483112	-3.49785553816328	7.09539540202189	0.00772822404188243	0	0.42321854074561
5:19412253|19472056	-6.72256499136888	-2.65499597431979	7.0899583310074	0.00775170495334329	0	0.42321854074561
9:13492161|13598089	-6.30654725571083	-2.98243003713085	6.46588024949127	0.0109965158338529	0	0.42321854074561

**_Question:_**
I'm curious whether the positive logFC value indicates an up-regulated circRNA in the case or control condition.

For example **6.69328375381015** is up regulated circRNA is case or in control condition?

**Comment by Kevinzjy** [comment]
Hi, @ravisaroch. The positive logFC means the circRNA is upregulated in the T group compared to the C group.
