### ISSUE TITLE
Question: Predict circRNAs using multiple tools

### ISSUE THREAD

**Issue by farzamani** [bioinfo-biols/CIRIquant#60]
Hi, 
I have a question regarding predicting circRNAs using multiple tools (CIRI2, find_circ, DCC, etc.) using CIRIquant.
How am I supposed to do that using CIRIquant `--circ` and `--tool` options? I am not sure if I can insert multiple parameters there.

Thanks!

**Comment by Kevinzjy** [comment]
Hi @farzamani , CIRIquant does not support specifying multiple `--circ` and `--tool` parameters at the same time. However, you could merge these results into a bed file for the `--bed` option.
